package com.liferay.devcon2013.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BeerDrinker service. Represents a row in the &quot;SBUT_BeerDrinker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.devcon2013.model.impl.BeerDrinkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.devcon2013.model.impl.BeerDrinkerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeerDrinker
 * @see com.liferay.devcon2013.model.impl.BeerDrinkerImpl
 * @see com.liferay.devcon2013.model.impl.BeerDrinkerModelImpl
 * @generated
 */
public interface BeerDrinkerModel extends BaseModel<BeerDrinker>,
    StagedGroupedModel, WorkflowedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a beer drinker model instance should use the {@link BeerDrinker} interface instead.
     */

    /**
     * Returns the primary key of this beer drinker.
     *
     * @return the primary key of this beer drinker
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this beer drinker.
     *
     * @param primaryKey the primary key of this beer drinker
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this beer drinker.
     *
     * @return the uuid of this beer drinker
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this beer drinker.
     *
     * @param uuid the uuid of this beer drinker
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the beer drinker ID of this beer drinker.
     *
     * @return the beer drinker ID of this beer drinker
     */
    public long getBeerDrinkerId();

    /**
     * Sets the beer drinker ID of this beer drinker.
     *
     * @param beerDrinkerId the beer drinker ID of this beer drinker
     */
    public void setBeerDrinkerId(long beerDrinkerId);

    /**
     * Returns the group ID of this beer drinker.
     *
     * @return the group ID of this beer drinker
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this beer drinker.
     *
     * @param groupId the group ID of this beer drinker
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this beer drinker.
     *
     * @return the company ID of this beer drinker
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this beer drinker.
     *
     * @param companyId the company ID of this beer drinker
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this beer drinker.
     *
     * @return the user ID of this beer drinker
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this beer drinker.
     *
     * @param userId the user ID of this beer drinker
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this beer drinker.
     *
     * @return the user uuid of this beer drinker
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this beer drinker.
     *
     * @param userUuid the user uuid of this beer drinker
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this beer drinker.
     *
     * @return the user name of this beer drinker
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this beer drinker.
     *
     * @param userName the user name of this beer drinker
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this beer drinker.
     *
     * @return the create date of this beer drinker
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this beer drinker.
     *
     * @param createDate the create date of this beer drinker
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this beer drinker.
     *
     * @return the modified date of this beer drinker
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this beer drinker.
     *
     * @param modifiedDate the modified date of this beer drinker
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the status of this beer drinker.
     *
     * @return the status of this beer drinker
     */
    @Override
    public int getStatus();

    /**
     * Sets the status of this beer drinker.
     *
     * @param status the status of this beer drinker
     */
    @Override
    public void setStatus(int status);

    /**
     * Returns the status by user ID of this beer drinker.
     *
     * @return the status by user ID of this beer drinker
     */
    @Override
    public long getStatusByUserId();

    /**
     * Sets the status by user ID of this beer drinker.
     *
     * @param statusByUserId the status by user ID of this beer drinker
     */
    @Override
    public void setStatusByUserId(long statusByUserId);

    /**
     * Returns the status by user uuid of this beer drinker.
     *
     * @return the status by user uuid of this beer drinker
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getStatusByUserUuid() throws SystemException;

    /**
     * Sets the status by user uuid of this beer drinker.
     *
     * @param statusByUserUuid the status by user uuid of this beer drinker
     */
    @Override
    public void setStatusByUserUuid(String statusByUserUuid);

    /**
     * Returns the status by user name of this beer drinker.
     *
     * @return the status by user name of this beer drinker
     */
    @AutoEscape
    @Override
    public String getStatusByUserName();

    /**
     * Sets the status by user name of this beer drinker.
     *
     * @param statusByUserName the status by user name of this beer drinker
     */
    @Override
    public void setStatusByUserName(String statusByUserName);

    /**
     * Returns the status date of this beer drinker.
     *
     * @return the status date of this beer drinker
     */
    @Override
    public Date getStatusDate();

    /**
     * Sets the status date of this beer drinker.
     *
     * @param statusDate the status date of this beer drinker
     */
    @Override
    public void setStatusDate(Date statusDate);

    /**
     * Returns the name of this beer drinker.
     *
     * @return the name of this beer drinker
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this beer drinker.
     *
     * @param name the name of this beer drinker
     */
    public void setName(String name);

    /**
     * Returns the alcohol level of this beer drinker.
     *
     * @return the alcohol level of this beer drinker
     */
    public float getAlcoholLevel();

    /**
     * Sets the alcohol level of this beer drinker.
     *
     * @param alcoholLevel the alcohol level of this beer drinker
     */
    public void setAlcoholLevel(float alcoholLevel);

    /**
     * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
     */
    @Override
    public boolean getApproved();

    /**
     * Returns <code>true</code> if this beer drinker is approved.
     *
     * @return <code>true</code> if this beer drinker is approved; <code>false</code> otherwise
     */
    @Override
    public boolean isApproved();

    /**
     * Returns <code>true</code> if this beer drinker is denied.
     *
     * @return <code>true</code> if this beer drinker is denied; <code>false</code> otherwise
     */
    @Override
    public boolean isDenied();

    /**
     * Returns <code>true</code> if this beer drinker is a draft.
     *
     * @return <code>true</code> if this beer drinker is a draft; <code>false</code> otherwise
     */
    @Override
    public boolean isDraft();

    /**
     * Returns <code>true</code> if this beer drinker is expired.
     *
     * @return <code>true</code> if this beer drinker is expired; <code>false</code> otherwise
     */
    @Override
    public boolean isExpired();

    /**
     * Returns <code>true</code> if this beer drinker is inactive.
     *
     * @return <code>true</code> if this beer drinker is inactive; <code>false</code> otherwise
     */
    @Override
    public boolean isInactive();

    /**
     * Returns <code>true</code> if this beer drinker is incomplete.
     *
     * @return <code>true</code> if this beer drinker is incomplete; <code>false</code> otherwise
     */
    @Override
    public boolean isIncomplete();

    /**
     * Returns <code>true</code> if this beer drinker is in the Recycle Bin.
     *
     * @return <code>true</code> if this beer drinker is in the Recycle Bin; <code>false</code> otherwise
     */
    @Override
    public boolean isInTrash();

    /**
     * Returns <code>true</code> if this beer drinker is pending.
     *
     * @return <code>true</code> if this beer drinker is pending; <code>false</code> otherwise
     */
    @Override
    public boolean isPending();

    /**
     * Returns <code>true</code> if this beer drinker is scheduled.
     *
     * @return <code>true</code> if this beer drinker is scheduled; <code>false</code> otherwise
     */
    @Override
    public boolean isScheduled();

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BeerDrinker beerDrinker);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BeerDrinker> toCacheModel();

    @Override
    public BeerDrinker toEscapedModel();

    @Override
    public BeerDrinker toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
