package com.liferay.devcon2013.model.impl;

import com.liferay.devcon2013.model.BeerDrinker;
import com.liferay.devcon2013.model.BeerDrinkerModel;
import com.liferay.devcon2013.model.BeerDrinkerSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BeerDrinker service. Represents a row in the &quot;SBUT_BeerDrinker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.devcon2013.model.BeerDrinkerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BeerDrinkerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeerDrinkerImpl
 * @see com.liferay.devcon2013.model.BeerDrinker
 * @see com.liferay.devcon2013.model.BeerDrinkerModel
 * @generated
 */
@JSON(strict = true)
public class BeerDrinkerModelImpl extends BaseModelImpl<BeerDrinker>
    implements BeerDrinkerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a beer drinker model instance should use the {@link com.liferay.devcon2013.model.BeerDrinker} interface instead.
     */
    public static final String TABLE_NAME = "SBUT_BeerDrinker";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "beerDrinkerId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "status", Types.INTEGER },
            { "statusByUserId", Types.BIGINT },
            { "statusByUserName", Types.VARCHAR },
            { "statusDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "alcoholLevel", Types.FLOAT }
        };
    public static final String TABLE_SQL_CREATE = "create table SBUT_BeerDrinker (uuid_ VARCHAR(75) null,beerDrinkerId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null,alcoholLevel DOUBLE)";
    public static final String TABLE_SQL_DROP = "drop table SBUT_BeerDrinker";
    public static final String ORDER_BY_JPQL = " ORDER BY beerDrinker.name ASC";
    public static final String ORDER_BY_SQL = " ORDER BY SBUT_BeerDrinker.name ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.liferay.devcon2013.model.BeerDrinker"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.liferay.devcon2013.model.BeerDrinker"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.liferay.devcon2013.model.BeerDrinker"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UUID_COLUMN_BITMASK = 4L;
    public static long NAME_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.liferay.devcon2013.model.BeerDrinker"));
    private static ClassLoader _classLoader = BeerDrinker.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            BeerDrinker.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _beerDrinkerId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private int _status;
    private long _statusByUserId;
    private String _statusByUserUuid;
    private String _statusByUserName;
    private Date _statusDate;
    private String _name;
    private float _alcoholLevel;
    private long _columnBitmask;
    private BeerDrinker _escapedModel;

    public BeerDrinkerModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static BeerDrinker toModel(BeerDrinkerSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        BeerDrinker model = new BeerDrinkerImpl();

        model.setUuid(soapModel.getUuid());
        model.setBeerDrinkerId(soapModel.getBeerDrinkerId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setStatus(soapModel.getStatus());
        model.setStatusByUserId(soapModel.getStatusByUserId());
        model.setStatusByUserName(soapModel.getStatusByUserName());
        model.setStatusDate(soapModel.getStatusDate());
        model.setName(soapModel.getName());
        model.setAlcoholLevel(soapModel.getAlcoholLevel());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<BeerDrinker> toModels(BeerDrinkerSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<BeerDrinker> models = new ArrayList<BeerDrinker>(soapModels.length);

        for (BeerDrinkerSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _beerDrinkerId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setBeerDrinkerId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _beerDrinkerId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return BeerDrinker.class;
    }

    @Override
    public String getModelClassName() {
        return BeerDrinker.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("beerDrinkerId", getBeerDrinkerId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("status", getStatus());
        attributes.put("statusByUserId", getStatusByUserId());
        attributes.put("statusByUserName", getStatusByUserName());
        attributes.put("statusDate", getStatusDate());
        attributes.put("name", getName());
        attributes.put("alcoholLevel", getAlcoholLevel());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long beerDrinkerId = (Long) attributes.get("beerDrinkerId");

        if (beerDrinkerId != null) {
            setBeerDrinkerId(beerDrinkerId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        Integer status = (Integer) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }

        Long statusByUserId = (Long) attributes.get("statusByUserId");

        if (statusByUserId != null) {
            setStatusByUserId(statusByUserId);
        }

        String statusByUserName = (String) attributes.get("statusByUserName");

        if (statusByUserName != null) {
            setStatusByUserName(statusByUserName);
        }

        Date statusDate = (Date) attributes.get("statusDate");

        if (statusDate != null) {
            setStatusDate(statusDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        Float alcoholLevel = (Float) attributes.get("alcoholLevel");

        if (alcoholLevel != null) {
            setAlcoholLevel(alcoholLevel);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getBeerDrinkerId() {
        return _beerDrinkerId;
    }

    @Override
    public void setBeerDrinkerId(long beerDrinkerId) {
        _beerDrinkerId = beerDrinkerId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public int getStatus() {
        return _status;
    }

    @Override
    public void setStatus(int status) {
        _status = status;
    }

    @JSON
    @Override
    public long getStatusByUserId() {
        return _statusByUserId;
    }

    @Override
    public void setStatusByUserId(long statusByUserId) {
        _statusByUserId = statusByUserId;
    }

    @Override
    public String getStatusByUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
            _statusByUserUuid);
    }

    @Override
    public void setStatusByUserUuid(String statusByUserUuid) {
        _statusByUserUuid = statusByUserUuid;
    }

    @JSON
    @Override
    public String getStatusByUserName() {
        if (_statusByUserName == null) {
            return StringPool.BLANK;
        } else {
            return _statusByUserName;
        }
    }

    @Override
    public void setStatusByUserName(String statusByUserName) {
        _statusByUserName = statusByUserName;
    }

    @JSON
    @Override
    public Date getStatusDate() {
        return _statusDate;
    }

    @Override
    public void setStatusDate(Date statusDate) {
        _statusDate = statusDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _columnBitmask = -1L;

        _name = name;
    }

    @JSON
    @Override
    public float getAlcoholLevel() {
        return _alcoholLevel;
    }

    @Override
    public void setAlcoholLevel(float alcoholLevel) {
        _alcoholLevel = alcoholLevel;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                BeerDrinker.class.getName()));
    }

    /**
     * @deprecated As of 6.1.0, replaced by {@link #isApproved}
     */
    @Override
    public boolean getApproved() {
        return isApproved();
    }

    @Override
    public boolean isApproved() {
        if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isDenied() {
        if (getStatus() == WorkflowConstants.STATUS_DENIED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isDraft() {
        if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isExpired() {
        if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isInactive() {
        if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isIncomplete() {
        if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isInTrash() {
        if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isPending() {
        if (getStatus() == WorkflowConstants.STATUS_PENDING) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean isScheduled() {
        if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
            return true;
        } else {
            return false;
        }
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            BeerDrinker.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public BeerDrinker toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (BeerDrinker) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        BeerDrinkerImpl beerDrinkerImpl = new BeerDrinkerImpl();

        beerDrinkerImpl.setUuid(getUuid());
        beerDrinkerImpl.setBeerDrinkerId(getBeerDrinkerId());
        beerDrinkerImpl.setGroupId(getGroupId());
        beerDrinkerImpl.setCompanyId(getCompanyId());
        beerDrinkerImpl.setUserId(getUserId());
        beerDrinkerImpl.setUserName(getUserName());
        beerDrinkerImpl.setCreateDate(getCreateDate());
        beerDrinkerImpl.setModifiedDate(getModifiedDate());
        beerDrinkerImpl.setStatus(getStatus());
        beerDrinkerImpl.setStatusByUserId(getStatusByUserId());
        beerDrinkerImpl.setStatusByUserName(getStatusByUserName());
        beerDrinkerImpl.setStatusDate(getStatusDate());
        beerDrinkerImpl.setName(getName());
        beerDrinkerImpl.setAlcoholLevel(getAlcoholLevel());

        beerDrinkerImpl.resetOriginalValues();

        return beerDrinkerImpl;
    }

    @Override
    public int compareTo(BeerDrinker beerDrinker) {
        int value = 0;

        value = getName().compareTo(beerDrinker.getName());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof BeerDrinker)) {
            return false;
        }

        BeerDrinker beerDrinker = (BeerDrinker) obj;

        long primaryKey = beerDrinker.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        BeerDrinkerModelImpl beerDrinkerModelImpl = this;

        beerDrinkerModelImpl._originalUuid = beerDrinkerModelImpl._uuid;

        beerDrinkerModelImpl._originalGroupId = beerDrinkerModelImpl._groupId;

        beerDrinkerModelImpl._setOriginalGroupId = false;

        beerDrinkerModelImpl._originalCompanyId = beerDrinkerModelImpl._companyId;

        beerDrinkerModelImpl._setOriginalCompanyId = false;

        beerDrinkerModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<BeerDrinker> toCacheModel() {
        BeerDrinkerCacheModel beerDrinkerCacheModel = new BeerDrinkerCacheModel();

        beerDrinkerCacheModel.uuid = getUuid();

        String uuid = beerDrinkerCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            beerDrinkerCacheModel.uuid = null;
        }

        beerDrinkerCacheModel.beerDrinkerId = getBeerDrinkerId();

        beerDrinkerCacheModel.groupId = getGroupId();

        beerDrinkerCacheModel.companyId = getCompanyId();

        beerDrinkerCacheModel.userId = getUserId();

        beerDrinkerCacheModel.userName = getUserName();

        String userName = beerDrinkerCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            beerDrinkerCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            beerDrinkerCacheModel.createDate = createDate.getTime();
        } else {
            beerDrinkerCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            beerDrinkerCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            beerDrinkerCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        beerDrinkerCacheModel.status = getStatus();

        beerDrinkerCacheModel.statusByUserId = getStatusByUserId();

        beerDrinkerCacheModel.statusByUserName = getStatusByUserName();

        String statusByUserName = beerDrinkerCacheModel.statusByUserName;

        if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
            beerDrinkerCacheModel.statusByUserName = null;
        }

        Date statusDate = getStatusDate();

        if (statusDate != null) {
            beerDrinkerCacheModel.statusDate = statusDate.getTime();
        } else {
            beerDrinkerCacheModel.statusDate = Long.MIN_VALUE;
        }

        beerDrinkerCacheModel.name = getName();

        String name = beerDrinkerCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            beerDrinkerCacheModel.name = null;
        }

        beerDrinkerCacheModel.alcoholLevel = getAlcoholLevel();

        return beerDrinkerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(29);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", beerDrinkerId=");
        sb.append(getBeerDrinkerId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append(", statusByUserId=");
        sb.append(getStatusByUserId());
        sb.append(", statusByUserName=");
        sb.append(getStatusByUserName());
        sb.append(", statusDate=");
        sb.append(getStatusDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", alcoholLevel=");
        sb.append(getAlcoholLevel());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(46);

        sb.append("<model><model-name>");
        sb.append("com.liferay.devcon2013.model.BeerDrinker");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>beerDrinkerId</column-name><column-value><![CDATA[");
        sb.append(getBeerDrinkerId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
        sb.append(getStatusByUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
        sb.append(getStatusByUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>statusDate</column-name><column-value><![CDATA[");
        sb.append(getStatusDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>alcoholLevel</column-name><column-value><![CDATA[");
        sb.append(getAlcoholLevel());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
